app/(auth)/login/_hooks/useLoginHandler.ts
app/(dashboard)/[id]/home/components/ModalEditTask/ModalEditTask.tsx
app/(dashboard)/[id]/home/components/ModalEditTask/NavbarSub/CoverBtn.tsx
app/(dashboard)/[id]/home/components/ModalEditTask/NavbarSub/NavbarSub.tsx
app/(dashboard)/[id]/home/components/ModalEditTask/NavbarSub/TaskIdBtn.tsx
app/(dashboard)/[id]/home/components/ModalEditTask/NavbarSub/TaskTypeBtn.tsx
app/(dashboard)/[id]/home/components/ModalEditTask/NavbarTop/Breadcrumbs.tsx
app/(dashboard)/[id]/home/components/ModalEditTask/NavbarTop/NavbarTop.tsx
app/(dashboard)/[id]/home/components/ModalEditTask/NavbarTop/RightSectionBtns.tsx
app/(dashboard)/[id]/home/components/ModalEditTask/NavbarTop/ShareBtn.tsx
app/(dashboard)/[id]/home/components/ModalEditTask/NavbarTop/SidebarExpandBn.tsx
app/(dashboard)/[id]/home/components/ModalEditTask/NavbarTop/SwitchTask.tsx
app/(dashboard)/[id]/home/components/ModalEditTask/NavbarTop/Timestamp.tsx
app/(dashboard)/[id]/home/components/ModalEditTask/Title/Title.tsx
app/(dashboard)/[id]/testowy-route/page.tsx
app/(dashboard)/ui/ButtonIcon.tsx
icons/icons.tsx

When user is logged in context gets userId updated.

8696xr9wu [feat] [style] created part of ui for modal which updates task. Also added global state change for login

---

app/(dashboard)/[id]/home/page.tsx
app/(dashboard)/[id]/testowy-route/components/ProjectsSection.tsx
app/layout.tsx
app/server-actions/types.ts
app/server-actions/workspace/createNewWorkspace.ts
app/sideBar-Menu/components/components-SideBarContainer/components-SideBarModal/ColorChoice.tsx
app/sideBar-Menu/components/components-SideBarContainer/components-SideBarModal/components-SpaceModal/SpaceModalBody.tsx
app/sideBar-Menu/components/components-SideBarContainer/components-SideBarModal/components-SpaceModal/SpaceModalFooter.tsx
app/sideBar-Menu/components/components-SideBarContainer/components-SideBarModal/components-SpaceModal/components-SpaceModalBody/DescriptionInput.tsx
app/sideBar-Menu/components/components-SideBarContainer/components-SideBarModal/components-SpaceModal/components-SpaceModalBody/IconAndNamePicker.tsx
app/sideBar-Menu/components/components-SideBarContainer/components-SideBarModal/components-SpaceModal/components-SpaceModalBody/PrivacyToggle.tsx
context/DataProvider/FormProviders/WorkspaceFormProvider.tsx
hooks/useCreateWorkspace.tsx

New provider WorkspaceFormProvider context\DataProvider\FormProviders\WorkspaceFormProvider.tsx

#8696yqwah [feat] implemented react-query mutation, created func to pass data to db and create new workspace, created new provider

---

app/sideBar-Menu/components/AddWorkspaceElement.tsx
app/sideBar-Menu/components/addWorkspaceElement-Component/ButtonRender.tsx
app/sideBar-Menu/components/addWorkspaceElement-Component/buttonsWorkSpaceModal.tsx
app/sideBar-Menu/components/components-SideBarContainer/WorkspaceButtons.tsx
app/sideBar-Menu/components/componentsMenuFileChanger/ButtonFileChanger.tsx
app/sideBar-Menu/components/componentsMenuFileChanger/MenuFileChanger.tsx
app/sideBar-Menu/components/componentsMenuFileChanger/buttonsMenuFileChanger.tsx
app/sideBar-Menu/components/componentsMenuListChanger/ButtonListChanger.tsx
app/sideBar-Menu/components/componentsMenuListChanger/MenuListChanger.tsx
app/sideBar-Menu/components/componentsMenuListChanger/buttonsMenuListChanger.tsx
app/sideBar-Menu/components/list-Components/ListModal.tsx
icons/icons.tsx

Pull V14 I added modal menus for projects and workspaces and enhanced the modal menu for adding a list.

---

app/sideBar-Menu/components/componentsMenuListChanger/ButtonListChanger.tsx

Pull V15 add delete modal 

---

app/sideBar-Menu/components/components-SideBarContainer/WorkspaceButtons.tsx
app/sideBar-Menu/components/componentsMenuListChanger/ButtonListChanger.tsx
app/sideBar-Menu/components/componentsMenuListChanger/DeleteProjectButton.tsx
context/DataProvider/DataProvider.tsx

#86972rf0c [feat] created feature which removes project from workspace

---

app/topBar-Nav/components/TopbarNav.tsx

added dynamic link based on userId

[fix] fixed wrong behavior where user was sent to login page instead of home page

---

app/(dashboard)/_components/SidebarContainer/components/WorkspaceButtons/WorkspaceButtons.tsx
context/DataProvider/DataProvider.tsx
hooks/useTaskQuery.ts

Refetch tasks on refresh

---

app/server-actions/spaces/createSpace.ts
app/server-actions/spaces/deleteSpace.ts
app/server-actions/spaces/getSpaceById.ts
app/server-actions/spaces/getSpaces.ts
app/server-actions/spaces/updateSpace.ts
app/server-actions/types.ts
app/server-actions/user/updateUser.ts
hooks/useUsersUpdateUser.ts

https://app.clickup.com/t/8697uap1w

Implement Spaces 

---

dataconnect/.dataconnect/schema/prelude.gql
firebase.json
y

dataconnect was an issue. This service do not work in our app

CU-86985wrj8 fix: fixed error when emultors didn't start

---

app/(dashboard)/_components/SidebarContainer/components/WorkspaceButtons/SpaceButtons.tsx
app/(dashboard)/_components/SidebarContainer/components/WorkspaceButtons/components/AddWorkspaceElement/components/MenuListChanger/components/ButtonListChanger.tsx
app/(dashboard)/_components/SidebarContainer/components/WorkspaceButtons/components/AddWorkspaceElement/components/MenuListChanger/components/DeleteListButton.tsx
app/(dashboard)/_components/SidebarContainer/components/WorkspaceButtons/components/ListElement.tsx
app/server-actions/List/deleteList.ts

…r list to match new structure

CU-8698c89gp [refactor]  changed files with project code for list to match new structure

---

app/(dashboard)/_components/SidebarContainer/components/WorkspaceButtons/components/AddWorkspaceElement/AddSpaceElement.tsx
app/server-actions/List/updateList.ts
app/server-actions/space/updateSpace.ts
app/server-actions/types.ts
context/DataProvider/DataProvider.tsx
hooks/useUpdateList.tsx
hooks/useUpdateSpace.tsx

Description: Due to monolithic structure of component AddSpaceElement i was forced to create script which checks if element user clicked is space or list. When element is clicked props are pass and element changes state to editable.

CU-8698uhdwv feat:  added update type mutation, changed list element to show btn when list is clicked, created server actions

---

app/(dashboard)/_components/SidebarContainer/components/SettingPreview/components/SettingDangerZone.tsx
app/server-actions/user/deleteUser.test.ts
app/server-actions/user/deleteUser.ts

When clicked user account is deleted as well workspace references to user.

CU-8698zdzvx [Feat] added logic to "Delete account" btn

---

app/HomeSpace/HomeContentV2.tsx

Some elements will be not currently developed

CU-869909pb8 [chore] Commented unused ui elements

---

app/(dashboard)/[id]/l/[projectId]/components/UsersList.tsx
app/(dashboard)/[id]/l/[projectId]/page.tsx
app/(dashboard)/_components/Task/TaskTableRow.tsx
app/server-actions/user2task/createUserAssociationToTask.ts

Also wrapped context around {workspaceId}/l/ route. Somehow context in layout do not always responded when user in UsersList has been added.

CU-86990b31a feat: created createUserAssociationToTask action and function to handle it

---

app/HomeSpace/AssignedContent.tsx
app/server-actions/user/getUserAssociations.ts
app/server-actions/user2workspace/getUserAssociation.ts
hooks/useGetTaskAssignedToUser.ts

created react-query hook to fetch data from user2task collection and placed it in AssignedContent component. It is not final version of component.

CU-86990b3fj feat: created read type firebase action and react-query hook to use it inside component

---

app/(dashboard)/_components/UsersManage/components/Search/SearchManageFull/InviteUserToWorkspace.tsx
hooks/useGetCurrentWorkspace.ts

user id from firestore/auth is somehow undefined when used raw with server files

CU-86996b3xk fix: changed source of user id and added react-query to InviteUserToWorkspace

---

app/(dashboard)/_components/UsersManage/components/ContentMenage/ContentManageFull.tsx

If user is Unregistered badge shows Pending

CU-86997a830 [feat] added conditional render to role badge

---

app/(dashboard)/[id]/l/[projectId]/components/UsersList.tsx

filter condition exludes all users with signUpFullName Unregistered

CU-8699853j0 feat: added another filter condition

---

README.md

added: new icons, section Zespół
updated: dependencies list
styled many minor elements and moved Usuwanie workspace img to next line changed text in project header

CU-869733pqu docs: updated docs

---

app/(dashboard)/_components/SidebarContainer/components/SettingPreview/components/SettingDangerZone.tsx
app/(dashboard)/_components/UsersManage/RemoveUserFromWorkspaceButton.tsx
app/(dashboard)/_components/UsersManage/UsersManage.tsx
app/(dashboard)/_components/UsersManage/components/ContentMenage/ContentManageFull.tsx
app/server-actions/user2workspace/deleteUserAssociation.test.ts
app/server-actions/user2workspace/deleteUserAssociation.ts
app/server-actions/user2workspace/deleteUserAssociationByUserId.ts
app/server-actions/user2workspace/getUserAssociationById.ts

Changed deleteUserAssociation to deleteUserAssociationByUserId to distinguish it from server action which delete user association based on association id in user2workspace collection

CU-86998zkyv [feat] created functionality which removes selected user from workspace

---

app/(dashboard)/_components/SidebarContainer/components/WorkspaceButtons/components/AddWorkspaceElement/components/MenuFileChanger/components/ButtonFileChanger.tsx
app/(dashboard)/_components/SidebarContainer/components/WorkspaceButtons/components/AddWorkspaceElement/components/MenuFileChanger/components/DeleteSpaceButton.tsx

Functionality worked but wrong button was set to launch script. Also changed query name so it match collection.

CU-8699am54n fix: changed index of btn

---

app/HomeSpace/Components/ComponentsAssignedContent/List.tsx

Visible groups instead of taking state only from button now updates also from local storage

CU-8699b1mc1 feat: updated visibleGropus state and added useEffect function
